### ISSUE TITLE
Specific Field Middleware Problem.

### ISSUE THREAD

**Issue by 7assenTlili** [prisma/graphql-middleware#33]
Hello,
let's say we have the following book type:
`type Book {
    title: String
    author: String
    pagecount: Int
    cover: Cover
  }`
A problem I've noticed in this implementation is that if a middleware is specific to a field (the Book query in our case), then this middleware will be executed 5 times. First time in the Book query resolver, then 4 more times for every field resolver in the Book type.

Is there any way how I can limit the middleware to only be executed once (for the Book query resolver only)? Or did I miss someting?

**Comment by maticzav** [comment]
Hey @7assenTlili 👋,

I suppose you've found the solution to your issue. Let me know if you need any help with it! 🙂

**Comment by madrahul1992** [comment]
@maticzav Hi, Would you help me with the solution as I am also facing the same issue. Middleware gets invoked for each field in output type?

**Comment by maticzav** [comment]
Hey @madrahul1992 👋,

The remainings of this issue might be confusing, let me explain. `graphql-middleware` wraps resolvers in middleware following a "waterfall" paradigm. What this means is that if you apply middleware to an entire schema, middleware will cover every field of every type in it. Same goes for type-down and field-specific middleware. Due to GraphQL's nature of execution fields are called multiple times - you can read more about that in the article below.

My wild guess for the solution to your problem would be

```ts
const middleware = {
  Query: someMiddleware,
  Mutation: someMiddleware,
}

const schemaWithMiddleware(schema, middleware)
```

I hope you can sort the idea out! Let me know if this fixed your problem. 🙂 

https://www.prisma.io/blog/graphql-server-basics-the-schema-ac5e2950214e
