### ISSUE TITLE
Bug: repeatedly calling middleware for each key of returning value

### ISSUE THREAD

**Issue by NarHakobyan** [prisma/graphql-middleware#54]
Hi everyone, first I want to thank you for this great library, I have used it with Apollo server, all worked great intend of repeatedly calling, it's calling middleware for each field returned from a handler, and `args` argument is empty

```typescript
export const authMiddleware = async (resolve, root, args, ctx: Context, info) => {
    const mutationField = info.schema.getMutationType();
    const mutationDefinition = mutationField.getFields()[info.fieldName];

    if (mutationDefinition && mutationDefinition.auth) {
        try {
            const token = ctx.headers['authorization'].replace('Bearer ', '');
            const data = await Crypto.decodeJwt<{ id: string }>(token);
            const user = await User.findOne(data.id);

            ctx.state.auth = {
                user,
                data,
                token
            };
        } catch (e) {
            throw new AuthenticationError('unauthorized');
        }
    }

    const data = await resolve(root, args, ctx, info);

    console.log(data);
    return data;
};
```

**Comment by maticzav** [comment]
Hey @NarHakobyan 👋,

I think you posted a fascinating question. Let me see if I understand you correctly; the problem you're having is that `graphql-middleware` is triggered for every field in your return type, correct? 

If that's the case, it's not because it would be a bug. This is how `graphql-middleware` works! GraphQL middleware applies a provided function to every field following the waterfall mechanism. This means that if you apply `authMiddleware` to a whole `Query`, it will be executed on every field run in `Query`. Furthermore, if you apply it to the entire schema, it will be called every time GraphQL reaches a resolver.

I hope this helped you solve your issue. 🙂

**Comment by NarHakobyan** [comment]
Ht @maticzav, this is code chunk of my `resolvers`, middleware. When middleware is calling for `me` handler in `mutationDefinition.auth` property exists, but when I am trying to get stories of user from `me`, it's also calling middleware for nested `stories ` but `mutationDefinition.auth` is not defined

**Comment by gigouni** [comment]
Hi @NarHakobyan , did you fixed your issue? I've got the same one but I don't know what's my mistake.

**Comment by NarHakobyan** [comment]
HI @gigouni , no it's still exists

**Comment by henry74** [comment]
You need to define your middleware to only apply to queries/mutations so it doesn't apply to every field in a result:
```
const myMiddleware = {
  Query: async (resolve, root, args, context, info) => {
    logger.debug(`THIS WILL ONLY APPLY TO QUERIES`);
    const result = await resolve(root, args, context, info);
   return result;
  },
  Mutation: async (resolve, root, args, context, info) => {
    logger.debug(`THIS WILL ONLY APPLY TO MUTATIONS`);
    const result = await resolve(root, args, context, info);
    return result;
  }
};
```
